name: CI Pipeline

on:
  push:
    branches: ['*']

  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Run Linting and Tests
    runs-on: ubuntu-latest
    container:
      image: apache/spark-py:latest
      options: --user root  # Ejecutar como root


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black
        run: |
          black --check .

      - name: Run Isort
        run: |
          isort --check-only .

      - name: Run Flake8
        run: |
          flake8 .

      - name: Run Pytest
        run: |
          python3 -m pytest ./tests/ --maxfail=5 --disable-warnings

